export default {
  papayaWhip:       '#FFF0D5',
  newYorkPink:      '#E18B73',
  flamingo:         '#EF503B',
  mangoTango:       '#e37c0e',
  supernova:        '#fcb339',
  chinook:          '#A9D7BF',
  madang:           '#BEE2A7',
  puertoRico:       '#31B8B5',
  blueStone:        '#125E68',
  hopbush:          '#c3679b',
  dullMagenta:      '#C84AAB',
  vividViolet:      '#9f309c',
  smokeOnTheWater:  '#3F235F',
};
