export const START_CANVAS = 'START_CANVAS';
export const STOP_CANVAS = 'STOP_CANVAS';

export const OPEN_LOGIN = 'OPEN_LOGIN';
export const CLOSE_LOGIN = 'CLOSE_LOGIN';
export const OPEN_SIGNUP = 'OPEN_SIGNUP';
export const CLOSE_SIGNUP = 'CLOSE_SIGNUP';
export const OPEN_SIGNUP_ALERT = 'OPEN_SIGNUP_ALERT';
export const CLOSE_SIGNUP_ALERT = 'CLOSE_SIGNUP_ALERT';


export const ADD_CHUNK = 'ADD_CHUNK';

export const TOGGLE_PLAY = 'TOGGLE_PLAY';

export const SELECT_CHUNK = 'SELECT_CHUNK';
export const REMOVE_CHUNK = 'REMOVE_CHUNK';
export const CLEAR_ALL_CHUNKS = 'CLEAR_ALL_CHUNKS';
export const UPDATE_SELECTED_CHUNK = 'UPDATE_SELECTED_CHUNK';
export const UPDATE_ONE_CHUNK = 'UPDATE_ONE_CHUNK';
