export const INIT_P5 = 'INIT_P5';

export const ADD_CHUNK = 'ADD_CHUNK';

export const TOGGLE_PLAY = 'TOGGLE_PLAY';

export const SELECT_CHUNK = 'SELECT_CHUNK';
export const REMOVE_CHUNK = 'REMOVE_CHUNK';
export const CLEAR_ALL_CHUNKS = 'CLEAR_ALL_CHUNKS';
export const UPDATE_SELECTED_CHUNK = 'UPDATE_SELECTED_CHUNK';
export const UPDATE_ONE_CHUNK = 'UPDATE_ONE_CHUNK';
